### PR TITLE
build images for amd64 and arm64 platform (for Apple Silicon, M1, M2)

### LINKED ISSUE #129: Will docker-yii2 Support arm devices?
Hello,
Does docker-yii2 plan to support arm devices like Raspberry Pi ?

### LINKED ISSUE #148: yiisoftware/yii2-php:7.4-fpm + mac m1 architecture
Can you build an image for the same architecture for m1 processors? In principle, I was able to rebuild locally by taking the original dockerfile and adding PHP_BASE_IMAGE_VERSION instead php:7.4.28-fpm@sha256:debf3848d5407dbdd45c2c01844f7ccc4e35902a0f6ff557dbc3e634b60e87e6 and getting a 10-fold increase in productivity. I think you will be able to do it more correctly.

### PR DESCRIPTION
**Pull request by albertborsos**
resolves #129
resolves #148 

I tested it on Docker Hub, you can try the built images with: `albertborsos/yii2-php:8.0-apache`

Images on Docker Hub: https://hub.docker.com/r/albertborsos/yii2-php/tags?page=1

You can check the final builds here: https://github.com/albertborsos/yii2-docker/actions/runs/4646430952

### CODE REVIEW

**Comment by albertborsos** [comment]
@schmunk42 I moved your updates from yii-docker to this PR. Thanks for your work!

**Review by schmunk42 — APPROVED** [review]

**Comment by schmunk42** [comment]
Thank you!

**Comment by michaelarnauts** [comment]
Not sure if this is related, but since this merge (and the newly published images), I can't seem to get an image from dockerhub.

```
$ docker pull yiisoftware/yii2-php:8.2-apache
8.2-apache: Pulling from yiisoftware/yii2-php
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by schmunk42** [comment]
Meh, same here: https://github.com/yiisoft/yii-docker/issues/34

I am looking into it...

**Comment by michaelarnauts** [comment]
awesome, thanks!

**Comment by albertborsos** [comment]
I tried it with with intel and silicon CPU-s, both works with my `albertborsos/yii2-php` images, which contains my first commit only.

So if we build and push it together, it works.

**Comment by schmunk42** [comment]
What do you guys think about this solution?
https://github.com/yiisoft/yii-docker/issues/34#issuecomment-1506826374

**Pull request merged**
