### PR TITLE
Fix symlink apache

### PR DESCRIPTION
**Pull request by rustamwin**

### CODE REVIEW

**Comment by schmunk42** [comment]
There is no /app/web folder on the image

**Comment by rustamwin** [comment]
If I created a container, the / var / www / html symlink would be incorrectly created
screenshot from 2018-06-04 15-39-48
here
https://github.com/yiisoft/yii2-docker/blob/fcd7fb1ab732f3377e5fc8faa137b1679c43c1f2/php/Dockerfile-debian#L99

**Comment by rustamwin** [comment]
Yes I think there is a defect in my PR.
but in some way the application needs to be checked (with or without application)

I think, an container should have an index page if you run it without application

**Comment by rustamwin** [comment]
Maybe it is necessary to narrow it down [https://github.com/yiisoft/yii2-app-advanced/pull/347](https://github.com/yiisoft/yii2-app-advanced/pull/347)
All into one container

**Comment by schmunk42** [comment]
> I think, an container should have an index page if you run it without application

Would not be the case for a CLI app btw. Also the page can't tell you more than that there is nothing.

> but in some way the application needs to be checked (with or without application)

I think this is pretty straightforward: https://github.com/yiisoft/yii2-docker/blob/master/docs/install-application-template.md

> Maybe it is necessary to narrow it down yiisoft/yii2-app-advanced#347

The reference application for this Docker image is https://github.com/yiisoft/yii2-app

**Comment by rustamwin** [comment]
> There is no /app/web folder on the image

@schmunk42 maybe this line should be removed completely

**Comment by rustamwin** [comment]
@schmunk42 
https://github.com/yiisoft/yii2-docker/blob/fcd7fb1ab732f3377e5fc8faa137b1679c43c1f2/php/Dockerfile-debian#L99

**Comment by schmunk42** [comment]
Another option would be to modify the Apache config.

Why would you change it?

Von meinem iPhone gesendet

**Comment by schmunk42** [comment]
> because there is no /app/web folder on the image

But there'll be one, when you add an application template.

**Pull request closed without merging**
