### PR TITLE
ci: fix mongodb version for php 5

### PR DESCRIPTION
**Pull request by odai-alali**
related #111

### CODE REVIEW

**Comment by schmunk42** [comment]
Fails sadly :(

CC @samdark How can we see the GHactions results here?

**Comment by odai-alali** [comment]
strange. It works [here](https://github.com/odai-alali/yii2-docker/actions/runs/396404216)

I'll check it out

**Comment by odai-alali** [comment]
has a workflow started on this repo?? the branch is on my fork, so the workflow will run only [here](https://github.com/odai-alali/yii2-docker/actions/runs/396404216) on my fork

**Comment by schmunk42** [comment]
Would also be cool if we could separate build and test into own steps, WDYT?

**Comment by odai-alali** [comment]
> Would also be cool if we could separate build and test into own steps, WDYT?

Makes sense, and reading the logs will be easier

**Comment by schmunk42** [comment]
I still have a hard time finding the action-results for the commits, where are the builds for #b075f43 :disappointed: ?

**Comment by odai-alali** [comment]
https://github.com/odai-alali/yii2-docker/actions/runs/396498835

Are you able to open this link

**Comment by schmunk42** [comment]
Yes, but I would like to have a direct link and overview in the PRs, like there is with Travis.

**Comment by schmunk42** [comment]
Thank you for the PR!

**Pull request merged**
