### PR TITLE
Enabled apache mod rewrite and Xdebug compilation from .env file

### PR DESCRIPTION
**Pull request by FabrizioCaldarelli**

### CODE REVIEW

**Comment by schmunk42** [comment]
Thank you!

I merged this as is, since I remember issues with later versions, this has to be incremented later.

**Comment by schmunk42** [comment]
I've removed the build arg, since it was already enabled by default

**Comment by FabrizioCaldarelli** [comment]
Are you sure that REWRITE was enabled by default? Because I checked that mod_rewrite was enabled only after calling this line:

`RUN a2enmod rewrite`

**Comment by schmunk42** [comment]
This lines should do this: https://github.com/yiisoft/yii2-docker/blob/master/php/Dockerfile-debian#L113 - but we may also add a test for this.

**Pull request merged**
