### PR TITLE
Added default index page for apache

### PR DESCRIPTION
**Pull request by rustamwin**

### CODE REVIEW

**Comment by dmirogin** [comment]
Next step will remove /var/www/html directory

**Comment by rustamwin** [comment]
@dmirogin see #44

**Comment by dmirogin** [comment]
Each PR must be considered as independent unit of changes.

**Comment by schmunk42** [comment]
Doesn’t really make sense to say: “welcome from Yii Framework” when there is no framework on the image.

**Comment by samdark** [comment]
Agree.

**Comment by rustamwin** [comment]
I think the index page should be

**Pull request closed without merging**
