### PR TITLE
Feature/build with mlocati

### LINKED ISSUE #131: Recent PHP 8 changes have broken imagick install in PHP 7.4 image
Hey all.

Today we had some failing pipelines that were using the `yii2-php:7.4-apache` image. Composer would fail due to an incompatible version of imagick. It was reporting that the installed version was `@PACKAGE_VERSION@`

I won't give you my build logs as there is an easy way to reproduce the problem without them.
I noticed that the problem was introduced on the new version of the image that was pushed 3 days ago (April 30th 2021) with digest `d0b43c241834`. I went back to a previous version of 7.4 and found `7.4-apache-21.3.1` from a month ago which does not display the problem.

**Old version:**
```
docker run --rm -ti yiisoftware/yii2-php:7.4-apache-21.3.1 php -i | grep “imagick module version”
imagick module version => 3.4.4
```

**New version:**
```
docker run --rm -ti yiisoftware/yii2-php:7.4-apache php -i | grep “imagick module version” 
imagick module version => @PACKAGE_VERSION@
```

I think I tracked it down to the following changes:
Issue: https://github.com/yiisoft/yii2-docker/issues/110
PR: https://github.com/yiisoft/yii2-docker/pull/123
Commit: https://github.com/yiisoft/yii2-docker/commit/c7c94e40b50aae8ad2287cf384a59cedf9b24292

Prior to the above change, imagick was installed with pecl. After the change it is installed by downloading a package from github.

When I follow the exact same install steps from a vanilla PHP 7.4 image, I get the same problem where `php -i` returns `@PACKAGE_VERSION@` instead of the version number. Interestingly the same occurs even when running it against a PHP 8 image. I guess that install method is broken/incomplete?

Also, is there a suitable immutable image tag that we should be using for this image?

Thanks,

Tom...

### PR DESCRIPTION
**Pull request by schmunk42**
fixes #131

### CODE REVIEW

**Comment by tfrancisci** [comment]
This change has removed the mysql package which is now breaking our builds in other ways. Was this intended? :)

**Comment by schmunk42** [comment]
Not at all :)

The requirements check passes?! https://github.com/yiisoft/yii2-docker/runs/2508946919?check_suite_focus=true#step:7:69

**Comment by tfrancisci** [comment]
The mysql PHP extension is there, but not the mysql client itself...

**The old image (From March 25th)**
```
docker run --rm -ti yiisoftware/yii2-php:7.4-apache-21.3.1 mysql --version
usermod: no changes
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**The image from this morning**
```
docker run --rm -ti yiisoftware/yii2-php:7.4-apache mysql --version
usermod: no changes
/usr/local/bin/docker-php-entrypoint: 28: exec: mysql: not found
```

**Comment by schmunk42** [comment]
So the PHP extension should still be there, but the `mysql` client ist missing right?

```
> docker run --rm -ti yiisoftware/yii2-php:7.4-apache php -i | grep mysql
Configure Command =>  './configure'  '--build=x86_64-linux-gnu' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-pear' '--with-libdir=lib/x86_64-linux-gnu' '--with-apxs2' '--disable-cgi' 'build_alias=x86_64-linux-gnu'
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
mysqlnd
mysqlnd => enabled
Version => mysqlnd 7.4.18
Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_caching_sha2_password,auth_plugin_sha256_password
API Extensions => pdo_mysql
PDO drivers => sqlite, mysql, pgsql
pdo_mysql
Client API version => mysqlnd 7.4.18
pdo_mysql.default_socket => no value => no value
```

It breaks BC (unintended), but I am not sure if we should readd all the database clients.

@yiisoft/reviewers Thoughts?

**Comment by bizley** [comment]
I would keep them out. Images should be as slim as possible, not everyone needs the clients.

**Comment by tfrancisci** [comment]
Our pipeline was created by a vendor who, I guess, saw that it was present and so used it. We are now moving our mysql client tasks to use a different image anyway (I agree that it does not make sense to leave them in here). We can move on from this problem now.

Thanks for your work in maintaining this repo!

**Comment by schmunk42** [comment]
> Our pipeline was created by a vendor who, I guess, saw that it was present and so used it. We are now moving our mysql client tasks to use a different image anyway (I agree that it does not make sense to leave them in here). We can move on from this problem now.
> 
> Thanks for your work in maintaining this repo!

You should be able to re-add it just by (or similar)

```
RUN apt-get install -y mysql-client
```

**Comment by marcovtwout** [comment]
@schmunk42 Thanks for the pointer.

Here's an example when building on Debian 10:
```
RUN apt-get update
RUN apt-get install -y default-mysql-client
```

**Pull request merged**
