### PR TITLE
ci: use docker login action

### LINKED ISSUE #108: github actions push fails
```
Error: Cannot perform an interactive login from a non TTY device
```

use https://github.com/marketplace/actions/build-and-push-docker-images instead

### PR DESCRIPTION
**Pull request by odai-alali**
closes #108

### CODE REVIEW

**Comment by schmunk42** [comment]
Thank you!

**Comment by odai-alali** [comment]
@samdark could you please  `DOCKERHUB_USER`,  `DOCKERHUB_PASS` add to repo secrets. Login to docker step is failing

```
Error: Username and password required
```

**Comment by schmunk42** [comment]
@samdark Looks like I do not have acces to Security/Settings

**Comment by samdark** [comment]
@schmunk42 now you do.

**Comment by odai-alali** [comment]
@schmunk42 could you please re-run the workflow after adding the secrets

**Comment by schmunk42** [comment]
@odai-alali Login is OK, but Action complains there is no image with corresponding tag, see https://github.com/yiisoft/yii2-docker/runs/1481346000?check_suite_focus=true#step:8:9

Do we need to "hand-over" the image to subsequent jobs/stages?

**Comment by schmunk42** [comment]
@odai-alali Could you also have another look, just this one worked: https://github.com/yiisoft/yii2-docker/runs/1481346240?check_suite_focus=true

Some jobs try to push the wrong flavour `apache' vs. `fpm`?!

**Comment by odai-alali** [comment]
@schmunk42 matrix env were set only for test job but they should be valid for all jobs. fixed in #111

**Pull request merged**
