### PR TITLE
ci: flavours env must be set for all jobs

### PR DESCRIPTION
**Pull request by odai-alali**
related #108

### CODE REVIEW

**Comment by samdark** [comment]
👍

**Comment by schmunk42** [comment]
Looks good, just 5.6 is failing.

https://github.com/yiisoft/yii2-docker/actions/runs/395949877

Can we ignore it, it's past EOL?

**Comment by samdark** [comment]
Yes, I think we safely can ignore everything that's not supported anymore: https://www.php.net/supported-versions.php

It's way less relevant to keep old versions in Docker.

**Comment by odai-alali** [comment]
I'm unable to ignore a red pipeline :). a fix for php 5 in #112

**Pull request merged**
