### PR TITLE
ci: add action to build docker images

### LINKED ISSUE #106: Migrate to GitHub actions
See https://github.com/yiisoft/yii2-docker/issues/104

### PR DESCRIPTION
**Pull request by odai-alali**
closes #106

### CODE REVIEW

**Comment by schmunk42** [comment]
I think we need to add an error variable for the commands in test stage, eg.

```
docker-compose ..... || ERROR=1
...
exit ERROR
```

and we should also have 8.0 with allowed to fail.

**Comment by odai-alali** [comment]
php 5 is failing as expected now. Pushing happens only on master and tag.

Check it out. It can be enhanced I think (takes a lot of time)

**Review by schmunk42 — APPROVED** [review]
LGTM! Thank you.

@samdark Do you need to make adjustments for GH actions first or can this be merged?

**Comment by odai-alali** [comment]
> I think we need to add an error variable for the commands in test stage, eg.
> 
> ```
> docker-compose ..... || ERROR=1
> ...
> exit ERROR
> ```
> 
> So a broken Xdebug installation would also fail.
> 
> and we should also have 8.0 with allowed to fail.

BTW, this was not needed. When the test fails, the step after it will not be executed without evaluation variable

**Comment by samdark** [comment]
Merged. I don't have any additions.

**Pull request merged**
