### PR TITLE
Mysql and phpmyadmin

### PR DESCRIPTION
**Pull request by FabrizioCaldarelli**
I've added mysql and phpmyadmin support, because they can be useful when testing yii app.

### CODE REVIEW

**Comment by samdark** [comment]
I don't think we need phpmyadmin in the container itself.

**Comment by schmunk42** [comment]
Thank you for your efforts, but I also think we don't need PHPmyAdmin, at least in this repo, since we're only building PHP images and don't even run database tests.

It might be an addition for `yii2-app`(s), but also there I'd just add a section to the docs how to setup. For example, we almost never use a PHPmyAdmin container, instead we use `open mysql://docker.host:port` to start a desktop client.

**Comment by FabrizioCaldarelli** [comment]
I agree with you, but there are also developers that don't use docker frequently and could need to test apps or changes based on mysql and complex tables. Yesterday I spent 30 minutes to adapt docker configuration to use mysql to test an issue about gii generator from model, and the only way to do it was to install mysql. To keep things splitted, I have not touched base env so who need to use it only for php can continue to work as before

**Comment by schmunk42** [comment]
Wouldn't `yii2-gii` be a better place to run those tests? (although there are no dockerized tests, yet)

Actually, I don't want to be a picky here, but you don't need PHPmyAdmin for **testing** you need it for **development**, right?

**Comment by FabrizioCaldarelli** [comment]
Yes, that docker env is addressed mainly to development and not for testing. Should we create a docker env only for development to help developers do not invent the wheel everytime?

**Comment by schmunk42** [comment]
@samdark I think this is related to https://github.com/yiisoft/yii2-docker/issues/19 - should we start a section about Docker in the Guide?

**Comment by samdark** [comment]
Yes, I think so.

**Pull request closed without merging**
